# Common
alias l='ls'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lal='ls -al'
alias t='tmux'
alias ta='tmux a'
alias td='tmux deta'
alias pa='ps aux'
alias pf='ps axjfe'
alias g='grep'
alias gv='grep -v'
alias gi='grep -i'
alias gvi='grep -vi'
alias giv='grep -iv'
alias g-='egrep -v "(^$|^#)"'

# alias
alias py='python3'
alias v='vim'
alias vv='vim ~/.vimrc'
alias p="tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1"
alias ww='wget --limit-rate=3000k'
# alias jq='python3 /path/to/jq.py'
alias rr='ranger'

# SSH
alias s='ssh'
alias sss='ssh -D 127.0.0.1:10099'
alias sp='ssh -o ProxyCommand="/usr/bin/nc -X 5 -x 127.0.0.1:10099 %h %p"'
function sa {
    agentCount=$(ps aux | grep ssh-agent | wc -l)
    if [ $agentCount -eq 2 ]
    then
        ssh-agent > ~/tmp-agent.sh
        chmod 600 ~/tmp-agent.sh
    else
        echo "Agent is already running"
    fi
}
alias saa='source ~/tmp-agent.sh'
function spp {
    ssh -L 127.0.0.1:$3:$2:$3 $1
}

# Git
alias gg='git grep'
alias q='git status'
alias gc='git commit'
alias ga='git add'
alias gre='git checkout --'
alias tt="tig"
alias tb="tig blame"
alias gg='git grep --ignore-case'
alias gd='git diff'

# Quick
# alias ch='chromium --proxy-server=socks5://xxxx:xxx --proxy-bypass-list=192.168.xx --ozone-platform-hint=auto'
alias ch='chromium --proxy-server=socks5://xxxx:xxx --proxy-bypass-list=192.168.xx.x,192.168.x.x --ozone-platform=wayland'
alias ccc='code --ozone-platform=wayland'
alias ee='rsync -avP ~/.tmux.conf ~/.vimrc'
alias kn='vim ~/.ssh/known_hosts'
alias nn='cd ~/works/xxxx'
alias mm='python3 -m rich.markdown'
alias mmm='markdown2'

function md {
    cat $1 | python3 -m rich.markdown
}

# PROXY
function terminalProxyStart() {
    export http_proxy=http://127.0.0.1:8118
    export https_proxy=http://127.0.0.1:8118
}
function noterminalProxy() {
    export http_proxy=
    export https_proxy=
}

function qqq() {
    tmux new-window
    tmux rename-windows "server"
    tmux send-keys "su" Enter
    tmux split-window -h
    tmux send-keys "su" Enter
    tmux select-layout even-veritical
    # tmux select-layout even-horizontal
    # tmux set synchronize-panes on
}

# ANSIBLE_RELATED
alias ae='ansible-vault encrypt_string'
alias av='ansible-vault view'
alias ac='ansible-vault create'

# EXPORTS
export PATH=$PATH
export EDITOR=vim
export LC_CTYPE=en_US.UTF-8
#export LC_ALL=en_US.UTF-8
export MOZ_ENABLE_WAYLAND=1

# Powerline
# powerline-daemon -q
# POWERLINE_BASH_CONTINUATION=1
# POWERLINE_BASH_SELECT=1
# . /usr/share/powerline/bindings/bash/powerline.sh

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
